// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTAOmeGdDc3DhO6V8UWR1QpmaV3nmpQbA',
    appId: '1:1024893978803:web:310fd4ea250402879008c6',
    messagingSenderId: '1024893978803',
    projectId: 'kat-chat-21ded',
    authDomain: 'kat-chat-21ded.firebaseapp.com',
    storageBucket: 'kat-chat-21ded.appspot.com',
    measurementId: 'G-PXXG59E5QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_RU421n6As9MfjJaL5auQou05q22KBy0',
    appId: '1:1024893978803:android:351d7c42d1f74a019008c6',
    messagingSenderId: '1024893978803',
    projectId: 'kat-chat-21ded',
    storageBucket: 'kat-chat-21ded.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIndb_FUZR2Qfsl2t_tBUZIJUN6X0Pnh4',
    appId: '1:1024893978803:ios:06df86d90870173b9008c6',
    messagingSenderId: '1024893978803',
    projectId: 'kat-chat-21ded',
    storageBucket: 'kat-chat-21ded.appspot.com',
    iosBundleId: 'com.example.katChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIndb_FUZR2Qfsl2t_tBUZIJUN6X0Pnh4',
    appId: '1:1024893978803:ios:ed3006650eadf0ae9008c6',
    messagingSenderId: '1024893978803',
    projectId: 'kat-chat-21ded',
    storageBucket: 'kat-chat-21ded.appspot.com',
    iosBundleId: 'com.example.katChat.RunnerTests',
  );
}
